### ISSUE TITLE
unexpected output for quadratic bilevel problem

### ISSUE THREAD

**Issue by etesio** [or-fusion/pao#44]
Hi all, first of all thank you very much for PAO. I think pyomo is in general a great tool, and the extension to bilevel problems looks wonderful.

I am trying to get my head around the PAO functioning compared to the pyomo.bilevel package, and though I am able to run simple tests I am getting unexpected results. I have a main which looks like

```
from pao.bilevel import solvers
import models

if __name__ == "__main__":
   # global quadratic bilevel
    solver = solvers.solver4.BilevelSolver4()    

    # BARD. Optimal values are x=2, y=1        
    print("Bard 5.1.1")
    model = models.bard_511()
    solver.options.solver = "cbc"        
    results = solver.solve(model)
    print('optimal x:\t', model.x.value)
    print('optimal y:\t', model.y.value)
    print('Is constraint 1 satisfied?\t', model.sub.c1.expr())
    print('Is constraint 2 satisfied?\t', model.sub.c2.expr())
    print('Is constraint 3 satisfied?\t', model.sub.c3.expr())
    print('Is constraint 4 satisfied?\t', model.sub.c4.expr())
    print('=====')

    # TESIUS BASIC MODEL. Optimal values are x = 20, y1=10, y2=0
    print("Tesius 1.0")
    model = models.tesius_10()
    solver.options.solver = "couenne"        
    results = solver.solve(model)
    print('optimal x:\t', model.x.value)
    print('optimal y1:\t', model.sub.y1.value)
    print('optimal y2:\t', model.sub.y2.value)
    print('Is constraint satisfied?\t', model.sub.c.expr())
    print('=====')
```

where `models.py` contains the definition for the "bard_511" and "tesius_10" models

```
from pyomo.environ import ConcreteModel, Var, Objective, Constraint, maximize, minimize
from pao.bilevel import SubModel


def bard_511():
    M = ConcreteModel()
    M.x = Var(bounds=(0,None))
    M.y = Var(bounds=(0,None))
    M.o = Objective(expr=M.x - 4*M.y)

    M.sub = SubModel(fixed=M.x)
    M.sub.o = Objective(expr=M.y)
    M.sub.c1 = Constraint(expr=-M.x - M.y <= -3)
    M.sub.c2 = Constraint(expr=-2*M.x +   M.y <=  0)
    M.sub.c3 = Constraint(expr= 2*M.x +   M.y <= 12)
    M.sub.c4 = Constraint(expr=-3*M.x + 2*M.y <= -4)

    return M

def tesius_10():
    M = ConcreteModel()
    M.x = Var(bounds=(0,25))
    M.sub = SubModel(fixed=M.x)    
    M.sub.y1 = Var(bounds=(0,11))
    M.sub.y2 = Var(bounds=(0,11))    

    M.o = Objective(expr=M.x*M.sub.y1, sense=maximize)
    M.sub.o = Objective(expr=M.x*M.sub.y1 + 20*M.sub.y2, sense=minimize)

    M.sub.c = Constraint(expr=M.sub.y1 + M.sub.y2 == 10)

    return M
```
The `tesius_10` aims at defining a problem where the "leader" maximizes `x*y1`, while the follower minimizes `x*y1 + 20*y2`. A constraint links the `y1` and `y2` variables, as their sum should equal 10. The economically optimal choice should be that the leader sets `x=20`, in order to make the follower indifferent between "turning on" `y1=10, y2=0 `and `y2=10-y1`. Should the leader "attempts" to raise x above the threshold level of 20, `y1` (and thus the upper objective function) would be unfavored against `y2`. This would be my expected result... but what I see from the execution of the main is

```
Tesius 1.0
WARNING: Unused arguments in the bigM map! These arguments were not used by
    the transformation:
        None
optimal x:       25.0
optimal y1:      11.0
optimal y2:      10.999999999999947
Is constraint satisfied?         False
```

Am I misunderstanding the way "bilevel" structure is represented by PAO? Or am I missing something else in the way PAO should be used?

Incidentally, the bard_511 test looks fine, i.e. I get the expected result (with the same `solver4`, using `cbc` or `couenne` if that matters)

Thanks a lot

Enrico

**Comment by whart222** [comment]
@etesio I've confirmed that this model works for Bard511 on the master branch.

Currently, PAO only supports conversion of quadratic problems to linear form, requiring that the upper-level variables be binary when participating in bilinear terms.

But I see how your example could be addressed given a solver like couenne.  I'll have to think through the problem transformation, but I think this shouldn't be difficult to setup.

In the meantime, I think the right thing to do is to close this ticket and open another focused on adding this functionality.
