### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by AliRafieePour** [or-fusion/pao#47]
Hi,

I hope you are doing very well.

I have seen you have added some examples of bilevel optimization problems in the bilevel/examples folder. This is great to see these examples, however, my issue is that we cannot solve them and we have no idea what solver we should use. I have seen on a question posted online that we need to transform our problem using TransformatonFactory to be able to be solved by a particular solver. Would you be able to either share a more real-world example of this so we could learn more or perhaps explain this? Unfortunately, not many examples are available to learn from.

Thanks,

**Comment by whart222** [comment]
See the latest online documentation, which now contains detailed examples of the use of PAO.

**Comment by AliRafieePour** [comment]
Is it this one https://pao.readthedocs.io/en/latest/
?
 I can't still find any examples about how transformations are done....
